model_name=(input('виберіть модель: '))

instaled_softaware=(input('виберіть операційну систему: '))
version_windows=(input('виберіть версію: '))
Ram=(input('виберіть кількість оперативної пам\'яті: '))
video_kard=(input('виберіть тип відеокарти: '))
screen_extencion=(input('виберіть розширенн екрану: '))
storage_disk_capacity=(input('виберіть обєм пам\'яті: '))
processor=(input('виберіть процесор: '))
print('модель',model_name,)
print('операційна система',instaled_softaware)
print('версія',version_windows)
print('оперативна пам\'ять',Ram)
print('відео карта',video_kard)
print('розширення екрану',screen_extencion)
print('обєм пам\'яті',storage_disk_capacity)
print('модель процесора',processor)